/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [SidnaDB]    Script Date: 7/16/2021 2:11:50 AM ******/
CREATE DATABASE [SidnaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SidnaDB', FILENAME = N'D:\kama\Sidna\Sidna\DB\SidnaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SidnaDB_log', FILENAME = N'D:\kama\Sidna\Sidna\DB\SidnaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SidnaDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SidnaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SidnaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SidnaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SidnaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SidnaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SidnaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SidnaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SidnaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SidnaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SidnaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SidnaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SidnaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SidnaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SidnaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SidnaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SidnaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SidnaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SidnaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SidnaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SidnaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SidnaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SidnaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SidnaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SidnaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SidnaDB] SET  MULTI_USER 
GO

ALTER DATABASE [SidnaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SidnaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SidnaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SidnaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SidnaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SidnaDB] SET QUERY_STORE = OFF
GO

USE [SidnaDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SidnaDB] SET  READ_WRITE 
GO


